
// This file was auto-generated by ML.NET Model Builder. 

using Prognoz;

    Console.WriteLine("Прогнозирование общего перепада давления с помощью машинного обучения");
    Console.WriteLine("Введите дату в формате ДД.ММ.ГГГГ");
    string data = Console.ReadLine();

for (int i = 0; i < 3; i++)
{
    string time = "";
    switch (i)
    {
        case 0:
            time = " 0:00";
            break;
        case 1:
            time = " 8:00";
            break;
        case 2:
            time = " 16:00";
            break;
    }
    MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
    {
        Date = String.Concat(data, time)        
    };

    // Make a single prediction on the sample data and print results
    var predictionResult = MLModel1.Predict(sampleData);

    Console.WriteLine($"Прогнозируемый перепад давления {data} в{time} : {predictionResult.Score}атм\n");
}

    


Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();